### ISSUE TITLE
PHP 7 does support ZTS

### ISSUE THREAD

**Issue by mgdm** [deuill/go-php#33]
I note the README says that PHP 7 has removed ZTS. That's not actually true, it's just that you don't need the TSRMLS macros sprinkled all over the place (and in fact on PHP 7 they just expand to nothing). I think you should be able to support ZTS mode in 7? Have you come across anything that didn't work?

**Comment by deuill** [comment]
Indeed, support was not [completely removed](https://github.com/php/php-src/commit/bdeb220f48825642f84cdbf3ff23a30613c92e86), but was very much refactored (possibly for the best).

Admittedly, ZTS support in `go-php` was never really tested, since getting ZTS-enabled builds of PHP means compiling your own, and I'm not sure many people are willing to do that (given the lack of binary packages). It may be worth revisiting, however, if there's interest.

I'll fix the wording on the README in the meanwhile.

**Comment by deuill** [comment]
Wording changed, underlying issue still remains.
